# Generated by Django 4.0.4 on 2022-05-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('sme', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=30)),
                ('link', models.TextField(default=None)),
                ('no_of_weeks', models.IntegerField(default=4)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
